const playerOne = {
    name: "M Starc",
    fullName: "Mitchell Starc",
    personalInformation: {
        bornDate: "January 30 1990",
        birthPlace: "Baulkham Hills, Sydney, New South Wales",
        height: "1.96 m",
        roleType: "Bowler",
        battingType: "Left Handed Bat",
        bowlingType: "Left-aram fast",
    },
    playerImages: {
        images: "/JavaScript/playerObject/starc.png",
    },
    iccRanking: {
        batting: {
            test: "-",
            odi: "-",
            t20: "-",
        },
        bowling: {
            test: "11",
            odi: "21",
            t20: "-",
        },
    },
    careerInformation: {
        iplTeam: [
            "Delhi Capitals",
            "Kolkata Knight Riders",
            "Royal Challengers Bengaluru",
        ],
        bblTeam: ["Sydney Thunder", "Sydney Sixers"],
        nationalTeam: ["Australia"],
        domesticTeam: [
            "Australia A",
            "New South Wales",
            "Yorkshire",
            "Australians",
            "Finch XI",
        ],
    },
    battingCareerSummary:{
        test:{
            match: "97",
            inning: "141",
            runs: "2276",
            bestFigure: "3837",
            highestScore: "99",
            average: "20.5",
            strikeRate: "59.32",
            nO: "30",
            four: "225",
            six: "49",
            50: "11",
            100: "0",
            200: "0",
        },
        odi:{
            match: "127",
            inning: "75",
            runs: "577",
            bestFigure: "744",
            highestScore: "52",
            average: "12.02",
            strikeRate: "77.56",
            nO: "27",
            four: "42",
            six: "14",
            50: "1",
            100: "0",
            200: "0", 
        },
        t20:{
            match: "65",
            inning: "21",
            runs: "98",
            bestFigure: "100",
            highestScore: "14",
            average: "9.8",
            strikeRate: "98.00",
            nO: "11",
            four: "4",
            six: "2",
            50: "0",
            100: "0",
            200: "0", 
        },
        ipl:{
            match: "51",
            inning: "23",
            runs: "111",
            bestFigure: "119",
            highestScore: "29",
            average: "10.09",
            strikeRate: "93.28",
            nO: "12",
            four: "11",
            six: "0",
            50: "0",
            100: "0",
            200: "0", 
        }
    },
    bowlingCareerSummary:{
        test:{
            match: "97",
            inning: "186",
            balls: "18701",
            runs: "10641",
            wicket: "387",
            highestScore: "14",
            average: "27.5",
            Econ: "3.41",
            sR: "48.32",
            bbI:"6/48",
            bbM: "11/94",
            '5W': "15",
            '10W':"2",
        },
        odi:{
            match: "127",
            inning: "127",
            balls: "6512",
            runs: "5712",
            wicket: "244",
            average: "23.41",
            Econ: "5.26",
            sR: "26.69",
            bbI:"6/28",
            bbM: "6/28",
            '5W': "09",
            '10W':"0",
        },
        t20:{
            match: "65",
            inning: "65",
            balls: "1458",
            runs: "1881",
            wicket: "79",
            average: "23.81",
            Econ: "7.74",
            sR: "18.46",
            bbI:"4/20",
            bbM: "4/20",
            '5W': "0",
            '10W':"0",
        },
        ipl:{
            match: "51",
            inning: "49",
            balls: "1047",
            runs: "1503",
            wicket: "65",
            average: "23.12",
            Econ: "8.61",
            sR: "16.11",
            bbI:"5/35",
            bbM: "5/35",
            '5W': "01",
            '10W':"0",
        },
    }

};

const playerTwo = {
    name: "Bumrah",
    fullName: "Jasprit Bumrah",
    personalInformation: {
        bornDate: "December 06 1993 ",
        birthPlace: "Ahmedabad Gujarat India",
        height: "-",
        roleType: "Bowler",
        battingType: "Right Handed Bat",
        bowlingType: "Right-aram fast",
    },
    playerImage:{
        images:"/JavaScript/playerObject/jB.png",
    },
    iccRanking: {
        batting: {
            test: "-",
            odi: "-",
            t20: "-",
        },
        bowling: {
            test: "1",
            odi: "-",
            t20: "39",
        },
    },
    careerInformation: {
        iplTeam: [
            "Mumbai Indians",
        ],
        nationalTeam: ["India"],
        domesticTeam: [
            "Gujarat",
            "West Zone",
            "India A",
            "India Green",
        ],
    },
    battingCareerSummary:{
        test:{
            match: "45",
            inning: "69",
            runs: "332",
            bestFigure: "741",
            highestScore: "34",
            average: "7.06",
            strikeRate: "44.81",
            nO: "22",
            four: "35",
            six: "11",
            50: "0",
            100: "0",
            200: "0",
        },
        odi:{
            match: "89",
            inning: "26",
            runs: "91",
            bestFigure: "159",
            highestScore: "16",
            average: "7.58",
            strikeRate: "57.24",
            nO: "14",
            four: "10",
            six: "1",
            50: "0",
            100: "0",
            200: "0", 
        },
        t20:{
            match: "70",
            inning: "8",
            runs: "8",
            bestFigure: "14",
            highestScore: "7",
            average: "2.67",
            strikeRate: "57.15",
            nO: "5",
            four: "1",
            six: "0",
            50: "0",
            100: "0",
            200: "0", 
        },
        ipl:{
            match: "145",
            inning: "31",
            runs: "68",
            bestFigure: "79",
            highestScore: "16",
            average: "9.71",
            strikeRate: "86.08",
            nO: "24",
            four: "5",
            six: "1",
            50: "0",
            100: "0",
            200: "0", 
        }
    },
    bowlingCareerSummary:{
        test:{
            match: "45",
            inning: "86",
            balls: "8630",
            runs: "3977",
            wicket: "205",
            average: "19.4",
            Econ: "2.77",
            sR: "42.1",
            bbI:"6/27",
            bbM: "09/86",
            '5W': "13",
            '10W':"0",
        },
        odi:{
            match: "89",
            inning: "88",
            balls: "4580",
            runs: "3509",
            wicket: "149",
            average: "23.55",
            Econ: "4.6",
            sR: "30.74",
            bbI:"6/19",
            bbM: "6/19",
            '5W': "02",
            '10W':"0",
        },
        t20:{
            match: "70",
            inning: "69",
            balls: "1509",
            runs: "1579",
            wicket: "89",
            average: "17.74",
            Econ: "6.28",
            sR: "16.96",
            bbI:"3/7",
            bbM: "3/7",
            '5W': "0",
            '10W':"0",
        },
        ipl:{
            match: "145",
            inning: "145",
            balls: "3337",
            runs: "4032",
            wicket: "183",
            average: "22.03",
            Econ: "7.25",
            sR: "18.23",
            bbI:"5/10",
            bbM: "5/10",
            '5W': "02",
            '10W':"0",
        },
    }

};


const playerThree = {
    name: "M Shami",
    fullName: "Mohammed Shami",
    personalInformation: {
        bornDate: "September 03 1990 ",
        birthPlace: "Amroha Uttar Pradesh India",
        height: "-",
        roleType: "Bowler",
        battingType: "Right Handed Bat",
        bowlingType: "Right-aram fast",
    },
    playerImages:{
        images:"/JavaScript/playerObject/shami.jpg",
    },
    iccRanking: {
        batting: {
            test: "-",
            odi: "-",
            t20: "-",
        },
        bowling: {
            test: "1",
            odi: "-",
            t20: "39",
        },
    },
    careerInformation: {
        iplTeam: [
            "Mumbai Indians",
        ],
        nationalTeam: ["India"],
        domesticTeam: [
            "Gujarat",
            "West Zone",
            "India A",
            "India Green",
        ],
    },
    battingCareerSummary:{
        test:{
            match: "45",
            inning: "69",
            runs: "332",
            bestFigure: "741",
            highestScore: "34",
            average: "7.06",
            strikeRate: "44.81",
            nO: "22",
            four: "35",
            six: "11",
            50: "0",
            100: "0",
            200: "0",
        },
        odi:{
            match: "89",
            inning: "26",
            runs: "91",
            bestFigure: "159",
            highestScore: "16",
            average: "7.58",
            strikeRate: "57.24",
            nO: "14",
            four: "10",
            six: "1",
            50: "0",
            100: "0",
            200: "0", 
        },
        t20:{
            match: "70",
            inning: "8",
            runs: "8",
            bestFigure: "14",
            highestScore: "7",
            average: "2.67",
            strikeRate: "57.15",
            nO: "5",
            four: "1",
            six: "0",
            50: "0",
            100: "0",
            200: "0", 
        },
        ipl:{
            match: "145",
            inning: "31",
            runs: "68",
            bestFigure: "79",
            highestScore: "16",
            average: "9.71",
            strikeRate: "86.08",
            nO: "24",
            four: "5",
            six: "1",
            50: "0",
            100: "0",
            200: "0", 
        }
    },
    bowlingCareerSummary:{
        test:{
            match: "45",
            inning: "86",
            balls: "8630",
            runs: "3977",
            wicket: "205",
            average: "19.4",
            Econ: "2.77",
            sR: "42.1",
            bbI:"6/27",
            bbM: "09/86",
            '5W': "13",
            '10W':"0",
        },
        odi:{
            match: "89",
            inning: "88",
            balls: "4580",
            runs: "3509",
            wicket: "149",
            average: "23.55",
            Econ: "4.6",
            sR: "30.74",
            bbI:"6/19",
            bbM: "6/19",
            '5W': "02",
            '10W':"0",
        },
        t20:{
            match: "70",
            inning: "69",
            balls: "1509",
            runs: "1579",
            wicket: "89",
            average: "17.74",
            Econ: "6.28",
            sR: "16.96",
            bbI:"3/7",
            bbM: "3/7",
            '5W': "0",
            '10W':"0",
        },
        ipl:{
            match: "145",
            inning: "145",
            balls: "3337",
            runs: "4032",
            wicket: "183",
            average: "22.03",
            Econ: "7.25",
            sR: "18.23",
            bbI:"5/10",
            bbM: "5/10",
            '5W': "02",
            '10W':"0",
        },
    }

};



//  console.log(`The top 5 best bowlers are ${JSON.stringify(playerOne)} and ${JSON.stringify(playerTwo)}`);

console.log(playerOne,playerTwo);

